# Generated by Django 3.2.18 on 2023-03-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20230322_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='creared_on',
            new_name='created_on',
        ),
    ]
